#!/bin/bash

# This file is part of ktools.
#
# ktools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ktools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ktools.  If not, see <http://www.gnu.org/licenses/>.

if [[ -z "$1" ]]; then
    echo Please specify an installation directory.
    exit 1
fi
DIR=$1
if [[ -d $DIR ]]; then
    echo $DIR already exists.
    exit 2
fi

TOPDIR=$(pwd)
cd $TOPDIR/lev && javac Lev.java
cd $TOPDIR/nmer && javac NMer.java
cd $TOPDIR

mkdir $DIR
cp crank/crank $DIR
cp nmergen/nmergen.pl $DIR
cp nmeran/nmeran.pl $DIR
cp ffp/ffp.pl $DIR
cp lev/*.class $DIR
cp nmer/*.class $DIR
cp finalfix/finalfix.pl $DIR
cp isolate/isolate.pl $DIR
cp sequential/sequential.pl $DIR
cp viewtimes/viewtimes.pl $DIR

echo Installation complete to $DIR.
